import type { User } from './definitions'
import type { Product } from './definitions'

export const SEED_USERS: User[] = [
  {
    id: 'fa51c76c-4368-49bd-8fc5-e5292119bc48',
    email: 'kalvinpaviel4@gmail.com',
    passwordHash: '$2b$12$G/iq.sln3.pbO5wp5Ntc6eSuI.FaP69Soux7H13iorIwAztnwPMHS',
    name: 'Kalvin Paviel',
    role: 'admin',
    createdAt: '2026-05-14T18:58:16.630Z',
  },
  {
    id: 'createur-demo-001',
    email: 'ambre.taxidermie@sadsat.fr',
    passwordHash: '',
    name: 'Ambre Vidal',
    role: 'créateur',
    bio: 'Taxidermiste et naturaliste passionnée. Je travaille uniquement avec des animaux trouvés naturellement décédés, en préservant leur beauté avec respect.',
    createdAt: '2026-05-01T10:00:00.000Z',
  },
  {
    id: 'createur-demo-002',
    email: 'leo.bijoux@sadsat.fr',
    passwordHash: '',
    name: 'Léo Marchetti',
    role: 'créateur',
    bio: "Orfèvre autodidacte formé à Florence. Mes pièces naissent d'un dialogue entre les techniques médiévales et une sensibilité contemporaine.",
    createdAt: '2026-05-02T10:00:00.000Z',
  },
  {
    id: 'createur-demo-003',
    email: 'sofia.bougies@sadsat.fr',
    passwordHash: '',
    name: 'Sofia Blanc',
    role: 'créateur',
    bio: "Créatrice de bougies artisanales depuis 2019. J'explore les matières — cire, pigments, huiles brutes — pour créer des objets qui durent au-delà de leur combustion.",
    createdAt: '2026-05-03T10:00:00.000Z',
  },
]

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'tax-001',
    name: 'Renard roux naturalisé',
    description:
      "Renard roux adulte naturalisé selon les techniques éthiques de la taxidermie contemporaine. Pièce issue d'un animal trouvé naturellement décédé, traité avec soin pour préserver l'éclat de son pelage et l'expression naturelle de son regard.\n\nMontage sur socle en bois flotté brut. Pièce unique numérotée.",
    price: 85000,
    universe: 'taxidermie',
    category: 'Mammifères',
    images: [
      'https://picsum.photos/seed/fox-sadsat/800/1000',
      'https://picsum.photos/seed/fox-sadsat-2/800/1000',
    ],
    stock: 1,
    status: 'disponible',
    serialNumber: 'SADSAT-TX-001',
    materials: 'Pelage naturel, yeux en verre, armature acier, socle bois flotté',
    dimensions: { hauteur: 38, largeur: 22, longueur: 65, poids: 1800 },
    createdBy: 'createur-demo-001',
    createdAt: '2026-05-01T10:00:00.000Z',
    updatedAt: '2026-05-01T10:00:00.000Z',
  },
  {
    id: 'tax-002',
    name: 'Hibou grand-duc en vol',
    description:
      "Grand-duc d'Europe naturalisé dans une posture d'envol saisissante. L'envergure déployée révèle le dégradé naturel de son plumage fauve et brun. Monté sur tige en acier patiné, l'oiseau semble suspendu dans son élan.\n\nTrouvé en Normandie, traité artisanalement à l'atelier.",
    price: 62000,
    universe: 'taxidermie',
    category: 'Oiseaux',
    images: [
      'https://picsum.photos/seed/owl-sadsat/800/1000',
      'https://picsum.photos/seed/owl-sadsat-2/800/1000',
    ],
    stock: 1,
    status: 'disponible',
    serialNumber: 'SADSAT-TX-002',
    materials: 'Plumage naturel, yeux en verre soufflé, tige acier patiné',
    dimensions: { hauteur: 45, largeur: 80, poids: 950 },
    createdBy: 'createur-demo-001',
    createdAt: '2026-05-02T10:00:00.000Z',
    updatedAt: '2026-05-02T10:00:00.000Z',
  },
  {
    id: 'tax-003',
    name: 'Crâne de cerf élaphe',
    description:
      'Crâne de cerf élaphe adulte, nettoyé et blanchi à la méthode naturelle. Le bois (ramure) est intact, conservant toute la complexité de ses fourches. Pièce brute et puissante, idéale en pièce maîtresse d\'une composition murale.\n\nProvenance : Forêt de Chambord.',
    price: 28000,
    universe: 'taxidermie',
    category: 'Crânes',
    images: [
      'https://picsum.photos/seed/skull-sadsat/800/1000',
      'https://picsum.photos/seed/skull-sadsat-2/800/1000',
    ],
    stock: 1,
    status: 'disponible',
    serialNumber: 'SADSAT-TX-003',
    materials: 'Os naturel, ramure de cerf',
    dimensions: { hauteur: 90, largeur: 55, longueur: 40, poids: 3200 },
    createdBy: 'createur-demo-001',
    createdAt: '2026-05-03T10:00:00.000Z',
    updatedAt: '2026-05-03T10:00:00.000Z',
  },
  {
    id: 'tax-004',
    name: 'Sphinx tête de mort',
    description:
      "Papillon Acherontia atropos — le célèbre sphinx tête de mort — monté sous cadre en chêne vieilli et verre antireflet. Le motif crânien naturel sur le thorax est d'une précision remarquable. Collecte éthique, élevage en captivité.\n\nCadre sur-mesure réalisé par un ébéniste local.",
    price: 9500,
    universe: 'taxidermie',
    category: 'Insectes',
    images: [
      'https://picsum.photos/seed/moth-sadsat/800/1000',
      'https://picsum.photos/seed/moth-sadsat-2/800/1000',
    ],
    stock: 2,
    status: 'disponible',
    serialNumber: 'SADSAT-TX-004',
    materials: 'Papillon naturalisé, chêne massif, verre antireflet',
    dimensions: { hauteur: 25, largeur: 30, profondeur: 4, poids: 380 },
    createdBy: 'createur-demo-001',
    createdAt: '2026-05-04T10:00:00.000Z',
    updatedAt: '2026-05-04T10:00:00.000Z',
  },
  {
    id: 'bij-001',
    name: 'Bague entrelacée Ouroboros',
    description:
      "Bague sculptée à la main en argent 925 rhodié. Deux fils de métal s'entrelacent pour former un anneau infini, symbole du cycle éternel. La surface légèrement martelée capte et diffracte la lumière à chaque mouvement.\n\nChaque pièce est unique, les irrégularités du martelage lui confèrent son caractère.",
    price: 18000,
    universe: 'bijoux',
    category: 'Bagues',
    images: [
      'https://picsum.photos/seed/ring-sadsat/800/1000',
      'https://picsum.photos/seed/ring-sadsat-2/800/1000',
    ],
    stock: 3,
    status: 'disponible',
    serialNumber: 'SADSAT-BJ-001',
    materials: 'Argent 925 rhodié, finition martelée à la main',
    dimensions: { diametre: 1.8, poids: 4 },
    createdBy: 'createur-demo-002',
    createdAt: '2026-05-05T10:00:00.000Z',
    updatedAt: '2026-05-05T10:00:00.000Z',
  },
  {
    id: 'bij-002',
    name: 'Collier maille serpentine',
    description:
      "Collier en maille serpentine tressée à la main, en laiton doré à l'or fin 24 carats. La souplesse et la fluidité de la chaîne épousent parfaitement les courbes du cou. Fermoir à ressort intégré, discret et solide.\n\nLongueur ajustable : 42 à 46 cm.",
    price: 24000,
    universe: 'bijoux',
    category: 'Colliers',
    images: [
      'https://picsum.photos/seed/necklace-sadsat/800/1000',
      'https://picsum.photos/seed/necklace-sadsat-2/800/1000',
    ],
    stock: 2,
    status: 'disponible',
    serialNumber: 'SADSAT-BJ-002',
    materials: 'Laiton doré or fin 24k, fermoir argent',
    dimensions: { longueur: 44, poids: 12 },
    createdBy: 'createur-demo-002',
    createdAt: '2026-05-06T10:00:00.000Z',
    updatedAt: '2026-05-06T10:00:00.000Z',
  },
  {
    id: 'bij-003',
    name: 'Bracelet maille byzantine',
    description:
      "Bracelet en argent sterling 925, réalisé en maille byzantine — une technique d'orfèvrerie médiévale d'une complexité remarquable. Chaque maillon est soudé et poli individuellement.\n\nFermoir à cliquet sécurisé. La rigidité souple du bracelet épouse parfaitement le poignet.",
    price: 16000,
    universe: 'bijoux',
    category: 'Bracelets',
    images: [
      'https://picsum.photos/seed/bracelet-sadsat/800/1000',
      'https://picsum.photos/seed/bracelet-sadsat-2/800/1000',
    ],
    stock: 2,
    status: 'disponible',
    serialNumber: 'SADSAT-BJ-003',
    materials: 'Argent 925, maille byzantine soudée, fermoir cliquet',
    dimensions: { longueur: 18, poids: 22 },
    createdBy: 'createur-demo-002',
    createdAt: '2026-05-07T10:00:00.000Z',
    updatedAt: '2026-05-07T10:00:00.000Z',
  },
  {
    id: 'bij-004',
    name: 'Créoles martelées en vermeil',
    description:
      "Boucles d'oreilles créoles en vermeil (argent 925 doré or 18k). La surface martelée à la main crée un jeu de reflets unique qui évolue avec la lumière et le mouvement. Un classique revisité avec une âme artisanale.\n\nDiamètre : 3 cm. Poids plume, confort toute la journée.",
    price: 13500,
    universe: 'bijoux',
    category: "Boucles d'oreilles",
    images: [
      'https://picsum.photos/seed/earring-sadsat/800/1000',
      'https://picsum.photos/seed/earring-sadsat-2/800/1000',
    ],
    stock: 4,
    status: 'disponible',
    serialNumber: 'SADSAT-BJ-004',
    materials: 'Argent 925 doré or 18k (vermeil), finition martelée',
    dimensions: { diametre: 3, poids: 3 },
    createdBy: 'createur-demo-002',
    createdAt: '2026-05-08T10:00:00.000Z',
    updatedAt: '2026-05-08T10:00:00.000Z',
  },
  {
    id: 'bou-001',
    name: 'Bougie soja Forêt Noire',
    description:
      "Bougie artisanale en cire de soja 100% naturelle et végétale. Parfumée aux huiles essentielles de sapin, cèdre et mousse de chêne — une forêt brumeuse en pot. Temps de combustion estimé à 45 heures.\n\nCoulée à la main dans un pot en verre teinté fumé réutilisable.",
    price: 3500,
    universe: 'bougies',
    category: 'Cire de soja',
    images: [
      'https://picsum.photos/seed/candle1-sadsat/800/1000',
      'https://picsum.photos/seed/candle1-sadsat-2/800/1000',
    ],
    stock: 8,
    status: 'disponible',
    serialNumber: 'SADSAT-BG-001',
    materials: 'Cire de soja, huiles essentielles naturelles, mèche en coton, pot verre fumé',
    dimensions: { hauteur: 9, diametre: 8, poids: 220 },
    createdBy: 'createur-demo-003',
    createdAt: '2026-05-09T10:00:00.000Z',
    updatedAt: '2026-05-09T10:00:00.000Z',
  },
  {
    id: 'bou-002',
    name: "Bougie cire d'abeille brute",
    description:
      "Bougie pilier en cire d'abeille pure, non blanchie, au naturel. La cire garde sa teinte miel dorée et son parfum subtil de propolis et de fleurs. Brûle lentement et proprement, sans fumée ni paraffine.\n\nApiculture locale, circuit court. Estampille en relief SADSAT.",
    price: 4500,
    universe: 'bougies',
    category: "Cire d'abeille",
    images: [
      'https://picsum.photos/seed/candle2-sadsat/800/1000',
      'https://picsum.photos/seed/candle2-sadsat-2/800/1000',
    ],
    stock: 6,
    status: 'disponible',
    serialNumber: 'SADSAT-BG-002',
    materials: "Cire d'abeille pure non blanchie, mèche coton naturel",
    dimensions: { hauteur: 12, diametre: 6, poids: 180 },
    createdBy: 'createur-demo-003',
    createdAt: '2026-05-10T10:00:00.000Z',
    updatedAt: '2026-05-10T10:00:00.000Z',
  },
  {
    id: 'bou-003',
    name: 'Pilier Monolithe — oud & encens',
    description:
      'Grande bougie pilier coulée en cire végétale mixte (soja + colza), teintée en noir charbon. Sa forme monolithique et sa surface intentionnellement irrégulière en font autant un objet décoratif qu\'une source de lumière.\n\nParfum : bois d\'oud, encens, poivre noir. Durée de combustion : ~80 heures.',
    price: 5500,
    universe: 'bougies',
    category: 'Piliers',
    images: [
      'https://picsum.photos/seed/candle3-sadsat/800/1000',
      'https://picsum.photos/seed/candle3-sadsat-2/800/1000',
    ],
    stock: 5,
    status: 'disponible',
    serialNumber: 'SADSAT-BG-003',
    materials: 'Cire soja et colza, pigment charbon, mèche coton, parfum oud et encens',
    dimensions: { hauteur: 20, diametre: 7, poids: 400 },
    createdBy: 'createur-demo-003',
    createdAt: '2026-05-11T10:00:00.000Z',
    updatedAt: '2026-05-11T10:00:00.000Z',
  },
  {
    id: 'bou-004',
    name: "Fondants Brume d'automne",
    description:
      "Lot de 6 fondants parfumés en cire de soja, idéaux pour les diffuseurs à chaleur douce. Parfum automnal : pomme mûre, cannelle de Ceylan, feuilles humides et bois séché.\n\nSans plastifiants ni parabènes. Emballage papier kraft recyclé.",
    price: 2200,
    universe: 'bougies',
    category: 'Fondants',
    images: [
      'https://picsum.photos/seed/candle4-sadsat/800/1000',
      'https://picsum.photos/seed/candle4-sadsat-2/800/1000',
    ],
    stock: 15,
    status: 'disponible',
    serialNumber: 'SADSAT-BG-004',
    materials: 'Cire de soja, huiles parfumées naturelles, emballage kraft recyclé',
    dimensions: { poids: 90 },
    createdBy: 'createur-demo-003',
    createdAt: '2026-05-12T10:00:00.000Z',
    updatedAt: '2026-05-12T10:00:00.000Z',
  },
]
